services:
  wajik-anime-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wajik-anime-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - BUN_ENV=production
